engines:
  detekt:
    rules:
      naming:
        FunctionNaming:
          active: true
          functionPattern: '[a-z][a-zA-Z0-9]*'
          ignoreAnnotated:
            - 'Composable'
          exclude:
            - '**/*Test.kt'
      style:
        MagicNumber:
          active: true
          ignoreAnnotated:
            - 'Composable'
          exclude:
            - '**/*Test.kt'
  markdownlint:
    rules:
      MD007:
        active: true
        indent: 2
        exclude:
          - "docs/**/*.md" 
  pylint:
    rules:
      W0104:
        active: true
    exclude:
      - "**/*.txt"
