engines:
  detekt:
    rules:
      naming:
        FunctionNaming:
          active: true
          functionPattern: '[a-z][a-zA-Z0-9]*'
          ignoreAnnotated:
            - 'Composable'
          exclude:
            - '**/*Test.kt' # Exclude all test files
      style:
        MagicNumber:
          active: true
          ignoreAnnotated:
            - 'Composable'
          exclude:
            - '**/*Test.kt' # Exclude all test files
