services:
  mongo:
    image: mongo:latest # Use the official MongoDB image
    container_name: mongo # Name the container
    ports:
      - "27017:27017" # Expose MongoDB for debugging or external access
    volumes:
      - mongo_data:/data/db # Persist MongoDB data
    networks:
      - app-network

  backend:
    build:
      context: ./backend # Path to the backend directory
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map container port 8080 to host port 8080
    depends_on:
      - mongo # Ensure MongoDB starts first
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017 # MongoDB connection string
      SPRING_DATA_MONGODB_DATABASE: packsimulator # MongoDB database name
    networks:
      - app-network

  frontend:
     build:
       context: ./application # Path to the application directory
       dockerfile: Dockerfile
     ports:
       - "3000:80" # Map nginx's default port 80 to host port 3000
     depends_on:
       - backend # Ensure the backend starts first
    #  environment:
    #    - BACKEND_API_URL=http://backend:8080 # Backend service name in Docker network
     networks:
       - app-network

volumes:
  mongo_data: # Define a volume for MongoDB data persistence

networks:
  app-network: # Define a shared network for all services
