site_name: Pokémon TCG Pack Simulator Documentation
nav:
  - Home: index.md
  - Guide: guide.md
  - API: api.md
  - Open Source: open_source.md
theme:
  name: material
markdown_extensions:
  - toc
  - tables
  - admonition
