spring:
  data:
    mongodb:
      database: packsimulator
      uri: mongodb://localhost:27017
  application:
    name: PackSimulator
  logging:
    level:
      root: info
      de.thro.packsimulator: debug
      org.springframework: warn
server:
  port: 8080
