site_name: Pokémon TCG Pack Simulator - Dokumentation
nav:
  - Start: index.md
  - Quick Start: guide.md
  - API: api.md
  - Open Source: open_source.md
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
markdown_extensions:
  - toc
  - tables
  - admonition
