site_name: Pokémon TCG Pack Simulator - Dokumentation
docs_dir: pages
nav:
  - Start: index.md
  - Einführung: introduction.md
  - Installation: installation.md
  - API-Dokumentation: api.md
  - Lizenz: license.md
  - Externe API: open_source.md
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
markdown_extensions:
  - toc
  - tables
  - admonition
