site_name: Pokémon TCG Pack Simulator - Dokumentation
docs_dir: pages
theme:
  name: material
  language: de
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
  icon:
    admonition:
      alert: material/alert-circle
markdown_extensions:
  - toc
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - awesome-nav
