site_name: Pokémon TCG Pack Simulator - Dokumentation
docs_dir: pages
nav:
  - Start: index.md
  - Einführung: introduction.md
  - Installation: installation.md
  - API-Dokumentation: api.md
  - Lizenz: license.md
  - Externe API: open_source.md
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  features:
    - content.code.copy
    - navigation.tabs
extra:
  navigation:
    previous: "Zurück"
    next: "Weiter"
markdown_extensions:
  - toc
  - tables
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences