name: Upload Coverage to Codacy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use Eclipse Temurin distribution
          java-version: '17' # Ensure this matches your project's JDK version

      # Step 2.5: Ensure Gradle Wrapper is Executable
      - name: Ensure Gradle Wrapper is Executable
        run: chmod +x application/gradlew

      # Step 3: Build the project and generate Kover XML report
      - name: Build and generate coverage report
        working-directory: application # Navigate into the application directory
        run: |
          ./gradlew koverXmlReport

      # Step 4: Run Codacy Coverage Reporter GitHub Action
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: application/build/reports/kover/report.xml
          # or a comma-separated list for multiple reports
          # coverage-reports: <PATH_TO_REPORT>, <PATH_TO_REPORT>
