name: Upload Coverage to Codacy

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      # Step 3: Ensure Gradle Wrapper is Executable
      - name: Ensure Gradle Wrapper is Executable
        run: chmod +x backend/gradlew

      # Step 4: Set permissions for backend directory
      - name: Set permissions for backend directory
        run: chmod -R 777 backend

      # Step 5: Build the project and generate Jacoco XML report
      - name: Build and generate coverage report
        working-directory: backend
        run: |
          ./gradlew test jacocoTestReport --continue

      # Step 6: Upload test report as artifact (for debugging)
      - name: Upload test report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: backend/build/reports/tests/test

      # Step 7: Upload coverage report to Codacy
      - name: Upload coverage to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
          -r backend/build/reports/jacoco/test/jacocoTestReport.xml

      # Step 8: Verify Codacy Coverage Upload
      - name: Verify Codacy Coverage Upload
        run: echo "Coverage report uploaded to Codacy"
