name: Upload Coverage to Codacy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use Eclipse Temurin distribution
          java-version: '17' # Ensure this matches your project's JDK version

      # Step 3: Build the project and generate Kover XML report
      - name: Build and generate coverage report
        working-directory: application # Navigate into the application directory
        run: |
          ./gradlew koverXmlReport

      # Step 4: Install Codacy Coverage Reporter and Upload Coverage Report
      - name: Upload coverage report to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }} # Ensure the token is securely passed
        run: |
          curl -Ls https://coverage.codacy.com/get.sh | bash
          ./codacy-coverage-reporter report \
            --project-token $CODACY_PROJECT_TOKEN \
            --commit-uuid $(git rev-parse HEAD) \
            --coverage-reports application/build/reports/kover/report.xml
