name: Upload Coverage to Codacy

on:
  push:
    branches:
      - dev # Trigger the workflow only on the 'dev' branch
  pull_request:
    branches:
      - master # Trigger the workflow for pull requests targeting the 'master' branch

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin" # Use Eclipse Temurin distribution
          java-version: "21" # Ensure this matches your project's JDK version

      # Step 3: Ensure Gradle Wrapper is Executable
      - name: Ensure Gradle Wrapper is Executable
        run: chmod +x backend/gradlew

      # Step 4: Build the project and generate Jacoco XML report
      - name: Build and generate coverage report
        working-directory: backend # Navigate into the backend directory
        run: |
          ./gradlew jacocoTestReport

      # Step 5: Upload coverage report to Codacy
      - name: Upload coverage to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }} # Use the token from GitHub secrets
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
          -r backend/build/reports/jacoco/test/jacocoTestReport.xml
