name: CI Pipeline with Unified Coverage Report

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - master

jobs:
  # Stage 1: Setup Environment and Checkout Code
  setup:
    name: Setup Environment and Checkout Code
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set permissions for Gradle Wrappers
      - name: Set Executable Permissions for Gradle Wrappers
        run: |
          chmod +x application/gradlew
          chmod +x backend/gradlew

  # Stage 2: Build and Test Backend
  build-backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    needs: setup

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Build and Test Backend
      - name: Build and Test Backend
        working-directory: backend
        run: ./gradlew test jacocoTestReport --continue

      # Step 3: Save Backend Coverage Report
      - name: Save Backend Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/build/reports/jacoco/test/jacocoTestReport.xml

  # Stage 3: Build Application
  build-application:
    name: Build Application
    runs-on: ubuntu-latest
    needs: setup

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Build Application
      - name: Build Application
        working-directory: application
        run: ./gradlew wasmJsBrowserDistribution --continue

      # Step 3: Save Application Coverage Preparation
#      - name: Save Application Coverage Preparation
#        uses: actions/upload-artifact@v4
#        with:
#          name: application-coverage
#          path: application/build # Save build artifacts for future tests

  # Stage 4: Merge Coverage Reports and Upload to Codacy
  merge-and-upload-coverage:
    name: Merge Coverage Reports and Upload to Codacy
    runs-on: ubuntu-latest
    needs: [build-backend]
#    needs: [build-backend, build-application]

    steps:
      # Step 1: Download Backend Coverage Report
      - name: Download Backend Coverage Report
        uses: actions/download-artifact@v4
        with:
          name: backend-coverage
          path: coverage/backend

      # Step 2: Download Application Coverage Preparation
#      - name: Download Application Coverage Preparation
#        uses: actions/download-artifact@v4
#        with:
#          name: application-coverage
#          path: coverage/application

      # Step 3: Merge Coverage Reports
#      - name: Merge Coverage Reports
#        run: |
#          mkdir -p coverage/merged
#          cp coverage/backend/jacocoTestReport.xml coverage/merged/combined-coverage.xml
          # Placeholder for merging logic if application coverage is added in the future

      # Step 4: Upload Combined Coverage Report to Codacy
      - name: Upload Combined Coverage to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
          -r backend/build/reports/jacoco/test/jacocoTestReport.xml
#          -r coverage/merged/combined-coverage.xml
