name: Continuous Integration

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - master

jobs:
  # Stage 1: Setup Environment and Checkout Code
  setup:
    name: Setup Environment and Checkout Code
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Show Last Commit Information
      - name: Show Last Commit
        run: |
          echo "Last Commit Information:"
          git log -1 --pretty=format:"%h - %an: %s"

  # Stage 2: Build and Test Backend
  build-backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    needs: setup

    services:
      mongo:
        image: mongo:8.0
        ports:
          - 27017:27017
        options: >-
          --bind_ip 0.0.0.0
          --replSet rs0
          --oplogSize 128
          --quiet

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Ensure Gradle Wrapper is Executable
      - name: Ensure Gradle Wrapper is Executable
        run: chmod +x backend/gradlew

      # Step 3: Start MongoDB Replica Set
      - name: Start MongoDB Replica Set
        run: |
          mongo --eval "rs.initiate()"

      # Step 4: Build and Test Backend
      - name: Build and Test Backend
        working-directory: backend
        run: ./gradlew test jacocoTestReport --continue

      # Step 5: Save Backend Coverage Report
      - name: Save Backend Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/build/reports/jacoco/test/jacocoTestReport.xml

  # Stage 3: Build Application
  build-application:
    name: Build Application
    runs-on: ubuntu-latest
    needs: setup

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Ensure Gradle Wrapper is Executable
      - name: Ensure Gradle Wrapper is Executable
        run: chmod +x application/gradlew

      # Step 3: Build Application
      - name: Build Application
        working-directory: application
        run: ./gradlew wasmJsBrowserDistribution --continue

  # Stage 4: Merge Coverage Reports and Upload to Codacy
  merge-and-upload-coverage:
    name: Merge Coverage Reports and Upload to Codacy
    runs-on: ubuntu-latest
    needs: [build-backend]

    steps:
      # Step 1: Download Backend Coverage Report
      - name: Download Backend Coverage Report
        uses: actions/download-artifact@v4
        with:
          name: backend-coverage
          path: coverage/backend

      # Step 2: Upload Combined Coverage Report to Codacy
      - name: Upload Combined Coverage to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
          -r coverage/backend/jacocoTestReport.xml
