name: CI Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - master

jobs:
  # Stage 1: Checkout Code
  checkout:
    name: Checkout Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

  # Stage 2: Set Up Environment
  setup:
    name: Set Up Environment
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Ensure Gradle Wrapper is Executable
        run: chmod +x backend/gradlew

      - name: Set Permissions for Backend Directory
        run: chmod -R 777 backend

  # Stage 3: Build and Test
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build and Run Tests
        working-directory: backend
        run: |
          ./gradlew test jacocoTestReport --continue

      - name: Upload Test Report (on Failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: backend/build/reports/tests/test/** # Upload all test reports
          include-hidden-files: true

  # Stage 4: Upload Coverage Report
  upload-coverage:
    name: Upload Coverage Report
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Upload Coverage to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
          -r backend/build/reports/jacoco/test/jacocoTestReport.xml

      - name: Verify Codacy Coverage Upload
        run: echo "Coverage report successfully uploaded to Codacy"
